# NPDESI challenge lab 9 task 1: Deploy Tenants with Ansible

- name: ENSURE TENANT TENANT-1 EXISTS ON NEXUS SWITCH
  hosts: nxos
  connection: local
  gather_facts: no

  vars:
    provider:
      username: cisco
      password: cisco
      transport: nxapi
      host: "{{ inventory_hostname }}"

  tasks:
    - name: ENSURE VRF TENANT1 EXISTS
      nxos_vrf:
        vrf: TENANT1
        provider: "{{ provider }}"
    - name: ENSURE VLAN 10 EXISTS
      nxos_vlan:
        vlan_id: 10
        name: TENANT1_VLAN
        provider: "{{ provider }}"
    - name: ENSURE SVI VLAN 10 EXISTS
      nxos_interface:
        interface: vlan 10
        provider: "{{ provider }}"
    - name: ENSURE SVI VLAN 10 IS IN VRF TENANT1
      nxos_vrf_interface:
        interface: vlan 10
        vrf: TENANT1
        provider: "{{ provider }}"
    - name: ENSURE SVI VLAN 10 HAS IP 10.1.10.1/24
      nxos_ip_interface:
        interface: vlan 10
        addr: 10.1.10.1
        mask: 24
        provider: "{{ provider }}"
    - name: ENSURE ETHERNET2/24 IS UP AND L2
      nxos_interface:
        interface: Ethernet2/24
        mode: layer2
        provider: "{{ provider }}"
    - name: ENSURE INTERFACE2/24 IS IN VLAN 10
      nxos_switchport:
        interface: Ethernet2/24
        mode: access
        access_vlan: 10
        provider: "{{ provider }}"

